#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
In this problem set you work with cities infobox data, audit it, come up with a
cleaning idea and then clean it up. In the first exercise we want you to audit
the datatypes that can be found in some particular fields in the dataset.
The possible types of values can be:
- NoneType if the value is a string "NULL" or an empty string ""
- list, if the value starts with "{"
- int, if the value can be cast to int
- float, if the value can be cast to float, but CANNOT be cast to int.
   For example, '3.23e+07' should be considered a float because it can be cast
   as float but int('3.23e+07') will throw a ValueError
- 'str', for all other values

The audit_file function should return a dictionary containing fieldnames and a
SET of the types that can be found in the field. e.g.
{"field1": set([type(float()), type(int()), type(str())]),
 "field2": set([type(str())]),
  ....
}
The type() function returns a type object describing the argument given to the
function. You can also use examples of objects to create type objects, e.g.
type(1.1) for a float: see the test function below for examples.

Note that the first three rows (after the header row) in the cities.csv file
are not actual data points. The contents of these rows should note be included
when processing data types. Be sure to include functionality in your code to
skip over or detect these rows.
"""
import codecs
import csv
import json
import pprint

CITIES = 'cities.csv'

FIELDS = ["name", "timeZone_label", "utcOffset", "homepage", "governmentType_label",
          "isPartOf_label", "areaCode", "populationTotal", "elevation",
          "maximumElevation", "minimumElevation", "populationDensity",
          "wgs84_pos#lat", "wgs84_pos#long", "areaLand", "areaMetro", "areaUrban"]


def audit_file(filename, fields):
    fieldtypes = {}


    with open(filename, "r") as f:
        reader = csv.DictReader(f)
        '''Skip 3 rows'''
        for i in range(2):
            reader.next()

        headers = reader.fieldnames
        print headers
        #print headers
        for row in reader:
            for header in FIELDS:
                type = []
                field = row[header]
                type = validate_type(field)

                #if header == 'areaLand':
                    #print field, type

                if fieldtypes.has_key(header):
                    print ("key present :"+header)
                    orginal_type = fieldtypes[header]
                    print ("before :")
                    print (orginal_type)
                    if orginal_type != None:
                        print ("after0=")
                        print tuple(type)
                        orginal_type.update(tuple(type))
                        print ("after1 :")
                        print (orginal_type)
                        fieldtypes[header] = orginal_type
                        print ("after :")
                        print (fieldtypes[header])
                    else:
                        print "Null Original Type :"
                else:
                    print ("key not present :" + header)
                    #print type
                    fieldtypes[header] = set(type)
                    print fieldtypes[header]

    #print fieldtypes
    return fieldtypes


def validate_type(field):
    types = []

    if field == 'NULL' or field =='':
        types.append(type(None))
    elif str(field).startswith('{'):
        types.append(type([]))
    else:
        try:
            if int(field):
                types.append(type(1))
        except ValueError:
            try:
                float(field)
                types.append(type(1.1))
            except ValueError:
                print("ValueError")
                #types.append(type("string"))



    return types



def main():
    fieldtypes = audit_file(CITIES, FIELDS)

    pprint.pprint(fieldtypes)

    assert fieldtypes["areaLand"] == set([type(1.1), type([]), type(None)])
    assert fieldtypes['areaMetro'] == set([type(1.1), type(None)])


if __name__ == "__main__":
    lst = {"1","2"}
    #print type(lst)
    main()
